use crate::app::AudioQuality;
use crate::youtube_downloader::{YoutubeMusicDownload, YoutubeMusicDownloader};
use bytes::Bytes;
use futures::{Stream, TryStreamExt};
use std::ffi::OsString;
use std::io::Write;
use std::ops::Deref;
use std::path::{Path, PathBuf};
use std::process::Stdio;
use std::sync::Arc;
use std::time::Instant;
use tokio::io::{AsyncBufReadExt, BufReader};
use tokio::process::Child;
use tracing::{debug, error, info, warn};

const ESTIMATED_AUDIO_SIZE_BYTES: usize = 4 * 1024 * 1024; // 4MB estimate

/// Lazy cache for browser source detection — evaluated at most once, never at startup.
static BROWSER_SOURCE_CACHE: std::sync::OnceLock<Option<String>> = std::sync::OnceLock::new();

/// Convert a raw YouTube cookie string (Cookie: header format) to a
/// Netscape-format cookie file and return the path.
///
/// Handles `Cookie: name=value; ...` and bare `name=value; ...` inputs.
/// Skips empty names/values as well as malformed tokens (no `=` sign).
fn write_netscape_cookie_file(cookie_str: &str) -> Option<PathBuf> {
    let s = cookie_str.trim();
    if s.is_empty() {
        return None;
    }
    let mut lines: Vec<String> = Vec::new();
    for line in s.lines() {
        let line = line.trim();
        if line.starts_with('#') || line.is_empty() {
            continue;
        }
        // Strip optional "Cookie:" prefix
        let line = line.strip_prefix("Cookie:").unwrap_or(line).trim();
        if line.is_empty() {
            continue;
        }
        // Check for Netscape (tab-separated) format first
        let fields: Vec<&str> = line.split('\t').collect();
        if fields.len() >= 7 {
            // Netscape format: domain flag path secure expiry name value
            let name = fields[5].trim();
            let value = fields[6].trim();
            if name.is_empty() || value.is_empty() {
                continue;
            }
            let secure = if value.starts_with("__Secure-") || value.starts_with("__Host-") {
                "TRUE"
            } else {
                fields[3].trim()
            };
            lines.push(format!(
                "{}\t{}\t{}\t{secure}\t{}\t{name}\t{value}",
                fields[0].trim(), fields[1].trim(), fields[2].trim(), fields[4].trim()
            ));
        } else {
            // Raw Cookie header format: "name=value; name2=value2"
            for kv in line.split(';') {
                let kv = kv.trim();
                if kv.is_empty() {
                    continue;
                }
                let Some((name, value)) = kv.split_once('=') else {
                    continue;
                };
                let name = name.trim();
                let value = value.trim();
                if name.is_empty() || value.is_empty() {
                    continue;
                }
                // Mark __Secure- / __Host- cookies as secure
                let secure = if name.starts_with("__Secure-") || name.starts_with("__Host-") {
                    "TRUE"
                } else {
                    "FALSE"
                };
                lines.push(format!(
                    ".youtube.com\tTRUE\t/\t{secure}\t4102444800\t{name}\t{value}"
                ));
            }
        }
    }
    if lines.is_empty() {
        return None;
    }
    // Use a nanosecond-granularity timestamp to avoid cross-test collisions
    // when tests run in parallel (all share the same PID).
    let id = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    let mut path = std::env::temp_dir();
    path.push(format!("youtui_cookies_{id}.txt"));

    let mut file = std::fs::File::create(&path).ok()?;
    writeln!(file, "# Netscape HTTP Cookie File").ok()?;
    writeln!(file, "# Generated by youtui for yt-dlp").ok()?;
    for line in &lines {
        writeln!(file, "{line}").ok()?;
    }
    debug!(path = %path.display(), count = lines.len(), "Wrote Netscape-format cookie file for yt-dlp");
    Some(path)
}

/// Detect a Firefox-compatible browser profile (Floorp first, then Firefox)
/// and return a `firefox:PROFILE_PATH` string for `--cookies-from-browser`.
/// Supports Linux, macOS, and Windows profile locations.
fn detect_browser_source() -> Option<String> {
    let home = std::env::var("HOME").ok()?;

    let candidates: Vec<PathBuf> = {
        let mut v = Vec::new();

        // Floorp — Firefox fork (checked first for user preference)
        v.push(Path::new(&home).join(".floorp"));  // Linux
        if cfg!(target_os = "macos") {
            v.push(Path::new(&home).join("Library/Application Support/Floorp"));  // macOS
        }
        #[cfg(target_os = "windows")]
        if let Some(appdata) = std::env::var_os("APPDATA") {
            v.push(Path::new(&appdata).join("Floorp"));  // Windows
        }

        // Standard Firefox
        v.push(Path::new(&home).join(".mozilla/firefox"));  // Linux
        if cfg!(target_os = "macos") {
            v.push(Path::new(&home).join("Library/Application Support/Firefox"));  // macOS
        }
        #[cfg(target_os = "windows")]
        if let Some(appdata) = std::env::var_os("APPDATA") {
            v.push(Path::new(&appdata).join("Mozilla/Firefox"));  // Windows
        }

        v
    };

    for root in &candidates {
        if root.is_dir() {
            if let Some(profile) = find_default_profile(root) {
                let source = format!("firefox:{}", profile.display());
                debug!(%source, "Detected browser profile for cookie extraction");
                return Some(source);
            }
        }
    }

    debug!("No Firefox-compatible browser profile found for cookie extraction");
    None
}

/// Find the default profile directory inside a browser's profile root.
fn find_default_profile(profiles_dir: &Path) -> Option<PathBuf> {
    // Try profiles.ini first
    let ini = profiles_dir.join("profiles.ini");
    if ini.is_file() {
        let content = std::fs::read_to_string(&ini).ok()?;
        let (mut path, mut is_default) = (None::<String>, false);
        for line in content.lines() {
            if line.starts_with('[') {
                if is_default {
                    if let Some(ref p) = path {
                        let full = profiles_dir.join(p);
                        if full.is_dir() {
                            return Some(full);
                        }
                    }
                }
                is_default = line.starts_with("[Profile");
                if !is_default { path = None; }
            } else if is_default {
                if line.starts_with("Default=") {
                    if !line.trim_end().ends_with('1') {
                        is_default = false;
                        path = None;
                    }
                } else if let Some(p) = line.strip_prefix("Path=").map(|s| s.trim().to_string()) {
                    path = Some(p);
                }
            }
        }
        // Last profile in file
        if let Some(ref p) = path {
            let full = profiles_dir.join(p);
            if full.is_dir() {
                return Some(full);
            }
        }
    }

    // Fallback: scan for *.default or *.default-default directories
    if let Ok(entries) = std::fs::read_dir(profiles_dir) {
        for entry in entries.flatten() {
            let p = entry.path();
            if p.is_dir() {
                let name = p.file_name()?.to_string_lossy();
                if name.ends_with(".default-default") || name.ends_with(".default") {
                    return Some(p);
                }
            }
        }
    }

    None
}

#[derive(Clone)]
#[allow(dead_code)]
/// # Note
/// Cheap to clone due to use of Arc to store internals.
pub struct YtDlpDownloader {
    yt_dlp_command: Arc<OsString>,
    po_token: Option<String>,
    cookie_path: Option<PathBuf>,
    audio_quality: AudioQuality,
    /// `--cookies-from-browser` argument, e.g. `"firefox:/path/to/profile"`
    browser_cookie_source: Option<String>,
    /// `--js-runtimes` argument, e.g. "node" or "deno"
    js_runtime: Option<String>,
}

#[derive(Debug)]
pub enum YtDlpDownloaderError {
    IoError { message: String },
    NoOutput,
    InvalidFilesizeOutput { output: String },
}

impl std::fmt::Display for YtDlpDownloaderError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            YtDlpDownloaderError::IoError { message } => {
                write!(f, "Error running yt-dlp - <{message}>")
            }
            YtDlpDownloaderError::NoOutput => {
                write!(
                    f,
                    "Error running yt-dlp - no output when output was expected"
                )
            }
            YtDlpDownloaderError::InvalidFilesizeOutput { output } => {
                write!(f, "Error parsing filesize output: {}", output)
            }
        }
    }
}

impl YtDlpDownloader {
    pub fn new(
        yt_dlp_command: String,
        po_token: Option<String>,
        cookie_str: Option<String>,
        audio_quality: AudioQuality,
        browser_cookie_source: Option<String>,
        js_runtime: Option<String>,
    ) -> Self {
        let cookie_path = cookie_str.and_then(|s| write_netscape_cookie_file(&s));
        Self {
            yt_dlp_command: Arc::new(yt_dlp_command.into()),
            po_token,
            cookie_path,
            audio_quality,
            browser_cookie_source,
            js_runtime,
        }
    }
    /// Build the yt-dlp argument list for streaming a song.
    /// Extracted for testability — any new flag or format change must be
    /// validated in tests before deploying.
    fn build_stream_args(&self, video_id: &str, audio_quality: &AudioQuality) -> Vec<String> {
        let format_string = match audio_quality {
            AudioQuality::Low => "bestaudio[ext=m4a]/bestaudio".to_string(),
            _ => "bestaudio[ext=m4a]/bestaudio/best".to_string(),
        };
        let mut args: Vec<String> = vec![
            "--ignore-config".into(),
            "--no-simulate".into(),
            "-q".into(),
            "--no-warnings".into(),
            "-f".into(),
            format_string,
            "-o".into(),
            "-".into(),
        ];
        if let Some(ref pt) = self.po_token {
            args.push("--extractor-args".into());
            args.push(format!("youtube:po_token={}", pt));
        }
        if let Some(ref cp) = self.cookie_path {
            args.push("--cookies".into());
            args.push(cp.to_string_lossy().into_owned());
        } else {
            let browser_source = self.browser_cookie_source.clone()
                .or_else(|| BROWSER_SOURCE_CACHE.get_or_init(detect_browser_source).clone());
            if let Some(ref bcs) = browser_source {
                args.push("--cookies-from-browser".into());
                args.push(bcs.clone());
            }
        }
        if let Some(ref js) = self.js_runtime {
            args.push("--js-runtimes".into());
            args.push(js.clone());
        }
        args.push("--".into());
        args.push(video_id.to_string());
        args
    }

    pub async fn get_version(self) -> Result<String, YtDlpDownloaderError> {
        let output = tokio::process::Command::new(self.yt_dlp_command.deref())
            .arg("--version")
            .output()
            .await
            .map_err(|e| YtDlpDownloaderError::IoError {
                message: format!("{e}"),
            })?;
        String::from_utf8(output.stdout).map_err(|e| YtDlpDownloaderError::InvalidFilesizeOutput {
            output: e.to_string(),
        })
    }
}

impl YoutubeMusicDownloader for YtDlpDownloader {
    type Error = YtDlpDownloaderError;

    async fn stream_song(
        &self,
        song_video_id: impl AsRef<str> + Send,
        audio_quality: AudioQuality,
    ) -> Result<
        YoutubeMusicDownload<impl Stream<Item = Result<Bytes, Self::Error>> + Send>,
        Self::Error,
    > {
        let command = self.yt_dlp_command.clone();
        async move {
            // Skip extractor args - they add API overhead without benefit
            let video_id = song_video_id.as_ref().to_string();
            info!(%video_id, "Starting yt-dlp stream_song");
            
            let stream_start = Instant::now();
            let stream_args = self.build_stream_args(
                song_video_id.as_ref(),
                &audio_quality,
            );
            
            debug!(%video_id, ?stream_args, "yt-dlp stream args");
            
            let proc = tokio::process::Command::new(command.deref())
                .args(stream_args)
                .stderr(Stdio::piped())
                .stdout(Stdio::piped())
                .spawn()
                .map_err(|e| {
                    error!(%video_id, error = %e, "Failed to spawn yt-dlp stream process");
                    YtDlpDownloaderError::IoError {
                        message: format!("{e}"),
                    }
                })?;
            
            let Child {
                stderr: Some(stderr),
                stdout: Some(stdout),
                ..
            } = proc
            else {
                error!(%video_id, "yt-dlp stream process missing stdout or stderr");
                return Err(YtDlpDownloaderError::NoOutput);
            };
            
            // Read stderr in background for error reporting
            let video_id_clone = video_id.clone();
            tokio::spawn(async move {
                let reader = BufReader::new(stderr);
                let mut lines = reader.lines();
                while let Ok(Some(line)) = lines.next_line().await {
                    if line.contains("ERROR") || line.contains("WARNING") {
                        warn!(video_id = %video_id_clone, %line, "yt-dlp stderr");
                    }
                }
            });
            
            // Fixed size for progress tracking. yt-dlp doesn't report total size
            // in its default output; 4MB approximates a 4min128kbps track.
            // This is purely cosmetic — playback does not depend on this value.
            let total_size_bytes = ESTIMATED_AUDIO_SIZE_BYTES;
            
            let video_id_for_stream = video_id.clone();
            let stream = tokio_util::io::ReaderStream::new(stdout).map_err(move |e| {
                error!(%video_id_for_stream, error = %e, "Stream error");
                YtDlpDownloaderError::IoError {
                    message: format!("{e}"),
                }
            });
            
            info!(%video_id, %total_size_bytes, stream_start_ms = %stream_start.elapsed().as_millis(), "yt-dlp stream started");
            Ok(YoutubeMusicDownload {
                total_size_bytes,
                song: stream,
            })
        }
        .await
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::youtube_downloader::yt_dlp::YtDlpDownloader;
    use crate::youtube_downloader::{YoutubeMusicDownload, YoutubeMusicDownloader};
    use crate::app::AudioQuality;
    use bytes::Bytes;
    use futures::StreamExt;
    use std::fs;

    // --- write_netscape_cookie_file tests ---

    #[test]
    fn test_write_netscape_rejects_empty() {
        assert!(write_netscape_cookie_file("").is_none());
        assert!(write_netscape_cookie_file("   ").is_none());
        assert!(write_netscape_cookie_file("\n\n").is_none());
    }

    #[test]
    fn test_write_netscape_strips_cookie_prefix() {
        let path = write_netscape_cookie_file("Cookie: SAPISID=abc123").unwrap();
        let content = fs::read_to_string(&path).unwrap();
        assert!(content.contains("SAPISID\tabc123"));
        assert!(!content.contains("Cookie:"));
        let _ = fs::remove_file(&path);
    }

    #[test]
    fn test_write_netscape_bare_format() {
        let path = write_netscape_cookie_file("SAPISID=abc123; __Secure-3PSID=def456").unwrap();
        let content = fs::read_to_string(&path).unwrap();
        assert!(content.contains("SAPISID\tabc123"));
        assert!(content.contains("__Secure-3PSID\tdef456"));
        // __Secure-* cookies get secure flag TRUE.
        // Line format: domain<TAB>flag<TAB>path<TAB>secure<TAB>expiry<TAB>name<TAB>value
        // secure flag (position 4) is before expiry+name: TRUE<TAB>4102444800<TAB>__Secure-3PSID
        assert!(content.contains("TRUE\t4102444800\t__Secure-3PSID"));
        // Non-__Secure cookie (SAPISID) gets secure flag FALSE
        assert!(content.contains("FALSE\t4102444800\tSAPISID"));
        let _ = fs::remove_file(&path);
    }

    #[test]
    fn test_write_netscape_skips_empty_values() {
        let path = write_netscape_cookie_file("SAPISID=abc123; EMPTY=").unwrap();
        let content = fs::read_to_string(&path).unwrap();
        assert!(content.contains("SAPISID\tabc123"));
        assert!(!content.contains("EMPTY"));
        let _ = fs::remove_file(&path);
    }

    #[test]
    fn test_write_netscape_domain_is_youtube() {
        let path = write_netscape_cookie_file("SAPISID=abc123").unwrap();
        let content = fs::read_to_string(&path).unwrap();
        assert!(content.starts_with("#"));
        assert!(content.contains(".youtube.com"));
        let _ = fs::remove_file(&path);
    }

    #[test]
    fn test_write_netscape_invalid_tokens_skip_line() {
        // A token without '=' should be silently skipped, not abort the batch
        let path = write_netscape_cookie_file("SAPISID=abc123; invalid_no_equal_sign").unwrap();
        let content = fs::read_to_string(&path).unwrap();
        // Valid cookie should be present
        assert!(content.contains("SAPISID\tabc123"));
        // Invalid token should not appear in output
        assert!(!content.contains("invalid_no_equal_sign"));
        let _ = fs::remove_file(&path);
    }

    #[test]
    fn test_write_netscape_real_world_format() {
        // Mimics the user's actual cookie.txt
        let raw = "Cookie: __Secure-ROLLOUT_TOKEN=abc123; SAPISID=def456; VISITOR_INFO1_LIVE=xyz789; PREF=f6=1&tz=UTC";
        let path = write_netscape_cookie_file(raw).unwrap();
        let content = fs::read_to_string(&path).unwrap();
        assert!(content.contains("__Secure-ROLLOUT_TOKEN\tabc123"));
        assert!(content.contains("SAPISID\tdef456"));
        assert!(content.contains("VISITOR_INFO1_LIVE\txyz789"));
        // PREF value contains = which should be preserved
        assert!(content.contains("PREF\tf6=1&tz=UTC"));
        let _ = fs::remove_file(&path);
    }

    // --- Browser detection tests ---

    #[test]
    fn test_find_default_profile_with_inifile() {
        let dir = std::env::temp_dir().join(format!("youtui_test_profiles_{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();

        // Create profiles.ini with two profiles, second is default
        std::fs::write(
            dir.join("profiles.ini"),
            "[Profile0]\nName=non-default\nPath=xxxx.random\nDefault=0\n\n[Profile1]\nName=default\nPath=yyyy.default\nDefault=1\n",
        )
        .unwrap();
        std::fs::create_dir_all(dir.join("yyyy.default")).unwrap();
        std::fs::create_dir_all(dir.join("xxxx.random")).unwrap();

        let result = find_default_profile(&dir);
        assert!(result.is_some());
        assert!(result.unwrap().ends_with("yyyy.default"));

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_find_default_profile_default_before_path() {
        let dir = std::env::temp_dir().join(format!("youtui_test_profiles2_{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();

        // Default=1 appears BEFORE Path= in the section
        std::fs::write(
            dir.join("profiles.ini"),
            "[Profile0]\nName=test\nDefault=1\nPath=zzzz.default\n",
        )
        .unwrap();
        std::fs::create_dir_all(dir.join("zzzz.default")).unwrap();

        let result = find_default_profile(&dir);
        assert!(result.is_some());
        assert!(result.unwrap().ends_with("zzzz.default"));

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_find_default_profile_no_ini_fallback() {
        let dir = std::env::temp_dir().join(format!("youtui_test_profiles3_{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();

        // No profiles.ini — must fall back to directory scan
        std::fs::create_dir_all(dir.join("abc123.default-default")).unwrap();
        std::fs::create_dir_all(dir.join("other.random")).unwrap();

        let result = find_default_profile(&dir);
        assert!(result.is_some());
        assert!(result.unwrap().ends_with("abc123.default-default"));

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_find_default_profile_no_default_dir() {
        // Empty directory should return None
        let dir = std::env::temp_dir().join(format!("youtui_test_profiles4_{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();

        assert!(find_default_profile(&dir).is_none());

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_find_default_profile_handles_default_zero() {
        let dir = std::env::temp_dir().join(format!("youtui_test_profiles5_{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();

        // Both profiles have Default flag; only Profile1 is default
        std::fs::write(
            dir.join("profiles.ini"),
            "[Profile0]\nDefault=0\nPath=notdefault.default\n\n[Profile1]\nDefault=1\nPath=actualdefault.default\n",
        )
        .unwrap();
        std::fs::create_dir_all(dir.join("notdefault.default")).unwrap();
        std::fs::create_dir_all(dir.join("actualdefault.default")).unwrap();

        let result = find_default_profile(&dir);
        assert!(result.is_some());
        assert!(result.unwrap().ends_with("actualdefault.default"));

        let _ = std::fs::remove_dir_all(&dir);
    }

    // --- YtDlpDownloader construction tests ---

    #[tokio::test]
    async fn test_yt_dlp_downloader_with_po_token() {
        let downloader = YtDlpDownloader::new("yt-dlp".to_string(), Some("test_po_token".to_string()), None, AudioQuality::default(), None, None);
        assert!(downloader.po_token.is_some());
        assert_eq!(downloader.po_token.unwrap(), "test_po_token");
    }

    #[tokio::test]
    async fn test_yt_dlp_downloader_without_po_token() {
        let downloader = YtDlpDownloader::new("yt-dlp".to_string(), None, None, AudioQuality::default(), None, None);
        assert!(downloader.po_token.is_none());
    }

    #[tokio::test]
    async fn test_yt_dlp_downloader_creates_cookie_file() {
        // Cookie: header format: "name=value"
        let downloader = YtDlpDownloader::new("yt-dlp".to_string(), None, Some("SAPISID=abc123".to_string()), AudioQuality::default(), None, None);
        assert!(downloader.cookie_path.is_some());
        let path = downloader.cookie_path.as_ref().unwrap();
        assert!(path.exists());
        let content = fs::read_to_string(path).unwrap();
        assert!(content.contains("SAPISID\tabc123"));
        // Cleanup
        let _ = fs::remove_file(path);
    }

    #[tokio::test]
    async fn test_yt_dlp_downloader_creates_cookie_file_netscape_format() {
        // Netscape tab-separated format (common from browser cookie exports)
        let cookie = ".youtube.com\tTRUE\t/\tTRUE\t1735689600\tSAPISID\tabc123\n.youtube.com\tTRUE\t/\tTRUE\t1735689600\t__Secure-3PSAPISID\tdef456";
        let downloader = YtDlpDownloader::new("yt-dlp".to_string(), None, Some(cookie.to_string()), AudioQuality::default(), None, None);
        assert!(downloader.cookie_path.is_some());
        let path = downloader.cookie_path.as_ref().unwrap();
        assert!(path.exists());
        let content = fs::read_to_string(path).unwrap();
        assert!(content.contains("SAPISID\tabc123"));
        assert!(content.contains("__Secure-3PSAPISID\tdef456"));
        // Secure flag should be TRUE for __Secure- cookies
        assert!(content.contains("__Secure-3PSAPISID\tdef456"));
        // Cleanup
        let _ = fs::remove_file(path);
    }

    #[tokio::test]
    async fn test_yt_dlp_downloader_no_cookie_file_when_none() {
        let downloader = YtDlpDownloader::new("yt-dlp".to_string(), None, None, AudioQuality::default(), None, None);
        assert!(downloader.cookie_path.is_none());
    }

    #[test]
    fn test_build_stream_args_no_print_flag() {
        let d = YtDlpDownloader::new("yt-dlp".to_string(), None, None, AudioQuality::default(), None, None);
        let args = d.build_stream_args("TEST_ID", &AudioQuality::default());
        assert!(!args.contains(&"--print".to_string()), "args must not contain --print: {args:?}");
    }

    #[test]
    fn test_build_stream_args_has_stdout_flag() {
        let d = YtDlpDownloader::new("yt-dlp".to_string(), None, None, AudioQuality::default(), None, None);
        let args = d.build_stream_args("TEST_ID", &AudioQuality::default());
        assert!(args.contains(&"-o".to_string()), "args must contain -o: {args:?}");
        let idx = args.iter().position(|a| a == "-o").unwrap();
        assert_eq!(args[idx + 1], "-", "-o must be followed by '-' for stdout: {args:?}");
    }

    #[test]
    fn test_build_stream_args_video_id_at_end() {
        let d = YtDlpDownloader::new("yt-dlp".to_string(), None, None, AudioQuality::default(), None, None);
        let args = d.build_stream_args("TEST_ID", &AudioQuality::default());
        assert_eq!(args.last(), Some(&"TEST_ID".to_string()), "video ID must be last arg: {args:?}");
    }

    #[test]
    fn test_build_stream_args_separator_before_video_id() {
        let d = YtDlpDownloader::new("yt-dlp".to_string(), None, None, AudioQuality::default(), None, None);
        let args = d.build_stream_args("TEST_ID", &AudioQuality::default());
        let sep_idx = args.iter().position(|a| a == "--").unwrap();
        assert_eq!(args[sep_idx + 1], "TEST_ID", "-- must precede video ID: {args:?}");
    }

    #[test]
    fn test_build_stream_args_low_quality_format() {
        let d = YtDlpDownloader::new("yt-dlp".to_string(), None, None, AudioQuality::default(), None, None);
        let args = d.build_stream_args("TEST_ID", &AudioQuality::Low);
        let f_idx = args.iter().position(|a| a == "-f").unwrap();
        assert_eq!(args[f_idx + 1], "bestaudio[ext=m4a]/bestaudio",
            "Low quality should use restricted format: {args:?}");
    }

    #[test]
    fn test_build_stream_args_high_quality_format() {
        let d = YtDlpDownloader::new("yt-dlp".to_string(), None, None, AudioQuality::default(), None, None);
        let args = d.build_stream_args("TEST_ID", &AudioQuality::High);
        let f_idx = args.iter().position(|a| a == "-f").unwrap();
        assert_eq!(args[f_idx + 1], "bestaudio[ext=m4a]/bestaudio/best",
            "High quality should use fallback chain: {args:?}");
    }

    #[test]
    fn test_build_stream_args_with_po_token() {
        let d = YtDlpDownloader::new("yt-dlp".to_string(), Some("TOKEN123".into()), None, AudioQuality::default(), None, None);
        let args = d.build_stream_args("TEST_ID", &AudioQuality::default());
        let e_idx = args.iter().position(|a| a == "--extractor-args").unwrap();
        assert_eq!(args[e_idx + 1], "youtube:po_token=TOKEN123",
            "extractor-args should include po_token: {args:?}");
    }

    #[test]
    fn test_build_stream_args_no_po_token_no_extractor_args() {
        let d = YtDlpDownloader::new("yt-dlp".to_string(), None, None, AudioQuality::default(), None, None);
        let args = d.build_stream_args("TEST_ID", &AudioQuality::default());
        assert!(!args.contains(&"--extractor-args".to_string()),
            "no extractor-args when po_token is None: {args:?}");
    }

    #[test]
    fn test_build_stream_args_with_cookie_path() {
        let d = YtDlpDownloader::new("yt-dlp".to_string(), None, Some("SAPISID=abc".into()), AudioQuality::default(), None, None);
        let args = d.build_stream_args("TEST_ID", &AudioQuality::default());
        // Cookie path should be Some (due to cookie construction in new())
        if let Some(ref cp) = d.cookie_path {
            let c_idx = args.iter().position(|a| a == "--cookies").unwrap();
            assert_eq!(args[c_idx + 1], cp.to_string_lossy(),
                "--cookies should point to cookie file: {args:?}");
        }
        // Should NOT have --cookies-from-browser when cookie_path is set
        assert!(!args.contains(&"--cookies-from-browser".to_string()),
            "no cookies-from-browser when --cookies is provided: {args:?}");
    }

    #[test]
    fn test_build_stream_args_with_js_runtime() {
        let d = YtDlpDownloader::new("yt-dlp".to_string(), None, None, AudioQuality::default(), None, Some("node".into()));
        let args = d.build_stream_args("TEST_ID", &AudioQuality::default());
        let j_idx = args.iter().position(|a| a == "--js-runtimes").unwrap();
        assert_eq!(args[j_idx + 1], "node", "js-runtimes arg should be node: {args:?}");
    }

    #[test]
    fn test_build_stream_args_no_js_runtime() {
        let d = YtDlpDownloader::new("yt-dlp".to_string(), None, None, AudioQuality::default(), None, None);
        let args = d.build_stream_args("TEST_ID", &AudioQuality::default());
        assert!(!args.contains(&"--js-runtimes".to_string()),
            "no js-runtimes when js_runtime is None: {args:?}");
    }

    #[tokio::test]
    #[ignore = "Network and yt-dlp required"]
    async fn test_downloading_a_song_with_ytdlp() {
        let downloader = YtDlpDownloader::new("yt-dlp".to_string(), None, None, AudioQuality::default(), None, None);
        let YoutubeMusicDownload { song: stream, .. } =
            downloader.stream_song("lYBUbBu4W08", AudioQuality::default()).await.unwrap();
        stream
            .map(|item| item.unwrap())
            .collect::<Vec<Bytes>>()
            .await;
    }
}
