use super::action::AppAction;
use crate::app::component::actionhandler::{
    Action, ActionHandler, Component, KeyRouter, Scrollable, TextHandler, YoutuiEffect,
};
use crate::app::effect::{Effects, MutationFn};
use crate::app::queue_persistence;
use crate::app::server::song_downloader::{
    cache_clear, create_decoder_from_cache, download_and_decode,
};
use crate::app::structures::{
    BrowserSongsList, DownloadStatus, ListSong, ListSongDisplayableField, ListSongID,
    Percentage, PlayState, SongListComponent,
};
use crate::app::ui::{AppCallback, WindowContext};
use crate::app::view::draw::{draw_loadable, draw_panel_mut, draw_table};
use crate::app::view::{BasicConstraint, DrawableMut, HasTitle, Loadable, TableView};
use crate::async_rodio_sink::{AllStopped, PlayUpdate, SeekDirection, Stopped, VolumeUpdate};
use futures::{Stream, StreamExt};
use crate::config::Config;
use crate::config::keymap::Keymap;
use crate::core::PoisonRecovery;
use crate::widgets::ScrollingTableState;
use crossterm::event::{KeyCode, KeyModifiers};
use notify_rust::{Notification, Timeout};
use rand::rngs::StdRng;
use rand::{Rng, SeedableRng};
use ratatui::Frame;
use ratatui::layout::Rect;
use ratatui::style::{Color, Style};
use ratatui::text::{Line, Span};
use rodio::Source;
use serde::{Deserialize, Serialize};
use std::borrow::Cow;
use std::cell::RefCell;
use std::collections::{HashMap, VecDeque};
use std::iter;
use std::sync::Arc;
use std::time::{Duration, SystemTime};
use tokio_stream::wrappers::UnboundedReceiverStream;
use tracing::{debug, error, warn};
use ytmapi_rs::common::YoutubeID;

#[cfg(test)]
mod tests;

const SONGS_AHEAD_TO_BUFFER: usize = 1;
const SONGS_BEHIND_TO_SAVE: usize = 0;
const GAPLESS_PLAYBACK_THRESHOLD: Duration = Duration::from_secs(1);
pub const DEFAULT_UI_VOLUME: Percentage = Percentage(50);

/// All cancellation errors from `song_downloader::download_and_decode` start
/// with "download cancelled".  Distinguishes expected scope-change cancellations
/// from real download failures.
fn is_cancellation_error(msg: &str) -> bool {
    msg.starts_with("download cancelled")
}

pub enum DownloadProgressUpdate {
    Downloading,
    Completed(Box<dyn Source<Item = f32> + Send + 'static>),
    Error(String),
}

/// Build an inverse visual→actual mapping for O(1) reverse lookups.
/// Given `indices[visual] == actual`, produces `map[actual] == Some(visual)`.
/// Entries without a visual position get `None`.
fn build_visual_map(indices: &[usize], list_len: usize) -> Vec<Option<usize>> {
    let mut map = vec![None; list_len];
    for (vis, &actual) in indices.iter().enumerate() {
        if actual < list_len {
            map[actual] = Some(vis);
        }
    }
    map
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum QueueState {
    NotQueued,
    Queued(ListSongID),
}

#[derive(Debug, Clone)]
pub struct DownloadTask {
    cancel_token: Arc<tokio_util::sync::CancellationToken>,
}

pub struct Playlist {
    pub list: BrowserSongsList,
    id_to_index_cache: HashMap<ListSongID, usize>,
    cur_played_dur: Option<Duration>,
    pub play_status: PlayState,
    pub queue_status: QueueState,
    volume: Percentage,
    cur_selected: usize,
    pub widget_state: ScrollingTableState,
    shuffle_enabled: bool,
    /// Visual → actual index mapping for shuffle mode. Generated by
    /// [`generate_shuffle_indices`]. Index `i` contains the list index that should
    /// appear at visual position `i` when shuffle is active.
    shuffle_indices: Vec<usize>,
    /// Seed used to generate [`shuffle_indices`]. Deterministic — same seed + same
    /// list length always produces the same shuffle order.
    shuffle_seed: u64,
    /// Inverse of [`shuffle_indices`] for O(1) `actual_to_visual_index` lookups.
    /// `shuffle_visual_map[actual] == Some(visual)` when shuffle is active.
    /// Rebuilt whenever `shuffle_indices` changes.
    shuffle_visual_map: Vec<Option<usize>>,
    // WARNING: std::sync::Mutex held in async context. Do NOT hold the lock across
    // any .await point — acquire, do sync work, drop, then .await. The usages below
    // are all verified safe (lock released before any await).
    active_downloads: Arc<std::sync::Mutex<Vec<(ListSongID, DownloadTask)>>>,
    download_queue: VecDeque<ListSongID>,
    search_enabled: bool,
    search_text: String,
    /// Visual → actual index mapping for search mode. When `search_text` is
    /// non-empty, this contains the list indices of matching songs in their
    /// natural order. Index `i` is the list index of the i‑th search result.
    /// When `search_text` is empty, this is `(0..len)` (all entries, natural order).
    search_indices: Vec<usize>,
    /// Inverse of [`search_indices`] for O(1) `actual_to_visual_index` lookups.
    /// `search_visual_map[actual] == Some(visual)` when search is active.
    /// Rebuilt whenever `search_indices` changes.
    search_visual_map: Vec<Option<usize>>,
    /// Saved `cur_selected` before search was activated — restored when search
    /// is closed so the previously highlighted item regains focus.
    pre_search_selected: usize,
    loaded_from_autosave: bool,
    preloaded_sources: HashMap<ListSongID, Box<dyn Source<Item = f32> + Send + 'static>>,
    play_next_queue: VecDeque<ListSongID>,
    resolving_audio: bool,
    resolve_remaining: usize,
    cached_row_numbers: Vec<String>,
    cached_title: RefCell<Option<Line<'static>>>,
}

impl Component for Playlist {}

#[derive(Clone, Copy, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PlaylistAction {
    ViewBrowser,
    PlaySelected,
    DeleteSelected,
    DeleteAll,
    ToggleShuffle,
    ToggleSearch,
    SaveQueue,
    LoadQueue,
    ClearSearch,
    ResolveAudioTracks,
    AddToPlayNext,
}

impl Action for PlaylistAction {
    fn context(&self) -> std::borrow::Cow<'_, str> {
        "Playlist".into()
    }

    fn describe(&self) -> std::borrow::Cow<'_, str> {
        match self {
            PlaylistAction::ViewBrowser => "View Browser",
            PlaylistAction::PlaySelected => "Play Selected",
            PlaylistAction::DeleteSelected => "Delete Selected",
            PlaylistAction::DeleteAll => "Delete All",
            PlaylistAction::ToggleShuffle => "Toggle Shuffle",
            PlaylistAction::ToggleSearch => "Toggle Search",
            PlaylistAction::ClearSearch => "Clear Search",
            PlaylistAction::SaveQueue => "Save Queue",
            PlaylistAction::LoadQueue => "Load Queue",
            PlaylistAction::ResolveAudioTracks => "Resolve Audio Tracks",
            PlaylistAction::AddToPlayNext => "Add To Play Next",
        }
        .into()
    }
}

impl ActionHandler<PlaylistAction> for Playlist {
    fn apply_action(&mut self, action: PlaylistAction) -> impl Into<YoutuiEffect<Playlist>> {
        match action {
            PlaylistAction::ViewBrowser => (Effects::none(), Some(self.view_browser())),
            PlaylistAction::PlaySelected => (self.play_selected(), None),
            PlaylistAction::DeleteSelected => (self.delete_selected(), None),
            PlaylistAction::DeleteAll => (self.delete_all(), None),
            PlaylistAction::ToggleShuffle => (self.toggle_shuffle(), None),
            PlaylistAction::ToggleSearch => (self.toggle_search(), None),
            PlaylistAction::ClearSearch => (self.clear_search(), None),
            PlaylistAction::SaveQueue => {
                if let Err(e) = queue_persistence::auto_save(self) {
                    warn!("Failed to auto-save queue: {e}");
                }
                (Effects::none(), None)
            }
            PlaylistAction::LoadQueue => match queue_persistence::auto_load(self) {
                Ok(effect) => (effect, None),
                Err(e) => {
                    error!("Failed to auto-load queue: {e}");
                    (Effects::none(), None)
                }
            },
            PlaylistAction::ResolveAudioTracks => {
                if self.resolving_audio {
                    return (Effects::none(), None);
                }
                let unchecked: Vec<ListSong> = self
                    .list
                    .get_list_iter_mut()
                    .filter_map(|s| {
                        if s.resolution_checked {
                            None
                        } else {
                            s.resolution_checked = true;
                            Some(s.clone())
                        }
                    })
                    .collect();
                if unchecked.is_empty() {
                    return (Effects::none(), None);
                }
                self.resolve_remaining = unchecked.len();
                self.resolving_audio = true;
                let mut effect = Effects::none();
                for _ in &unchecked {
                    effect = effect.push(Effects::new(
                        |_: &crate::app::server::ArcServer| async move {
                            Box::new(|_: &mut Playlist| Effects::none()) as Box<dyn FnOnce(&mut Playlist) -> Effects<Playlist> + Send>
                        }
                    ));
                }
                self.resolve_remaining = 0;
                self.resolving_audio = false;
                (effect, None)
            }
            PlaylistAction::AddToPlayNext => {
                if !self.search_text.is_empty() && self.search_indices.is_empty() {
                    return (Effects::none(), None);
                }
                if self.list.get_list_iter().len() == 0 {
                    return (Effects::none(), None);
                }
                let actual_index = self.visual_to_actual_index(self.cur_selected);
                let Some(id) = self.get_id_from_index(actual_index) else {
                    return (Effects::none(), None);
                };
                // Don't add currently playing song
                if self.get_cur_playing_id() == Some(id) {
                    return (Effects::none(), None);
                }
                // Don't add if already in play-next queue
                if self.play_next_queue.contains(&id) {
                    return (Effects::none(), None);
                }
                let song_title = self
                    .get_song_from_id(id)
                    .map(|s| s.title.clone())
                    .unwrap_or_default();
                self.play_next_queue.push_back(id);
                self.cached_title.borrow_mut().take();
                if !song_title.is_empty()
                    && let Ok(rt) = tokio::runtime::Handle::try_current()
                {
                    drop(rt.spawn(async move {
                        if let Err(e) = Notification::new()
                            .summary("Play Next")
                            .body(&song_title)
                            .appname("youtui")
                            .timeout(Timeout::Milliseconds(3000))
                            .show()
                        {
                            debug!("play-next notification failed: {e}");
                        }
                    }));
                }
                (Effects::none(), None)
            }
        }
    }
}

impl KeyRouter<AppAction> for Playlist {
    fn get_all_keybinds<'a>(
        &self,
        config: &'a Config,
    ) -> impl Iterator<Item = &'a Keymap<AppAction>> + 'a {
        self.get_active_keybinds(config)
    }

    fn get_active_keybinds<'a>(
        &self,
        config: &'a Config,
    ) -> impl Iterator<Item = &'a Keymap<AppAction>> + 'a {
        std::iter::once(&config.keybinds.playlist)
    }
}

impl TextHandler for Playlist {
    fn is_text_handling(&self) -> bool {
        self.search_enabled
    }

    fn get_text(&self) -> std::option::Option<&str> {
        if self.search_enabled {
            Some(&self.search_text)
        } else {
            None
        }
    }

    fn replace_text(&mut self, text: impl Into<String>) {
        self.search_text = text.into();
        self.update_search_indices();
        self.cached_title.borrow_mut().take();
    }

    fn clear_text(&mut self) -> bool {
        if !self.search_text.is_empty() {
            self.search_text.clear();
            self.update_search_indices();
            true
        } else {
            false
        }
    }

    fn handle_text_event_impl(
        &mut self,
        event: &crossterm::event::Event,
    ) -> Option<Effects<Self>> {
        if !self.search_enabled {
            return None;
        }

        match event {
            crossterm::event::Event::Key(key_event) => match key_event.code {
                KeyCode::Char('w') if key_event.modifiers == KeyModifiers::CONTROL => {
                    if !self.search_text.is_empty() {
                        let trimmed = self.search_text.trim_end().len();
                        let last_word_start = self.search_text[..trimmed]
                            .rfind(char::is_whitespace)
                            .map(|i| i + 1)
                            .unwrap_or(0);
                        self.search_text.truncate(last_word_start);
                        self.update_search_indices();
                        self.cached_title.borrow_mut().take();
                        self.cur_selected = self.cur_selected.min(self.get_max_visual_index());
                        Some(Effects::none())
                    } else {
                        None
                    }
                }
                KeyCode::Char(c) => {
                    self.search_text.push(c);
                    self.update_search_indices();
                    self.cached_title.borrow_mut().take();
                    self.cur_selected = self.cur_selected.min(self.get_max_visual_index());
                    Some(Effects::none())
                }
                KeyCode::Backspace => {
                    if !self.search_text.is_empty() {
                        self.search_text.pop();
                        self.update_search_indices();
                        self.cached_title.borrow_mut().take();
                        self.cur_selected = self.cur_selected.min(self.get_max_visual_index());
                        return Some(Effects::none());
                    }
                    None
                }
                KeyCode::Esc | KeyCode::Enter => {
                    self.search_enabled = false;
                    self.cached_title.borrow_mut().take();
                    Some(Effects::none())
                }
                _ => None,
            },
            _ => None,
        }
    }
}

impl DrawableMut for Playlist {
    fn draw_mut_chunk(&mut self, f: &mut Frame, chunk: Rect, selected: bool, cur_tick: u64) {
        draw_panel_mut(f, self, chunk, selected, |t, f, chunk| {
            draw_loadable(f, t, chunk, cur_tick, |t, f, chunk| {
                Some(draw_table(f, t, chunk, cur_tick))
            })
        });
    }
}

impl Loadable for Playlist {
    fn is_loading(&self) -> bool {
        false
    }
}

impl Scrollable for Playlist {
    fn increment_list(&mut self, amount: isize) {
        let max_index = self.get_max_visual_index();
        self.cur_selected = self
            .cur_selected
            .saturating_add_signed(amount)
            .min(max_index);
    }

    fn is_scrollable(&self) -> bool {
        true
    }
}

impl TableView for Playlist {
    fn get_selected_item(&self) -> usize {
        self.cur_selected
    }

    fn get_state(&self) -> &ScrollingTableState {
        &self.widget_state
    }

    fn get_layout(&self) -> &[BasicConstraint] {
        &[
            BasicConstraint::Length(3),
            BasicConstraint::Length(6),
            BasicConstraint::Length(3),
            BasicConstraint::Percentage(Percentage(33)),
            BasicConstraint::Percentage(Percentage(33)),
            BasicConstraint::Percentage(Percentage(33)),
            BasicConstraint::Length(9),
            BasicConstraint::Length(4),
        ]
    }

    fn get_items(&self) -> impl ExactSizeIterator<Item = impl Iterator<Item = Cow<'_, str>> + '_> {
        let count: usize = if !self.search_text.is_empty() {
            self.search_indices.len()
        } else if self.shuffle_enabled {
            self.shuffle_indices.len()
        } else {
            self.list.get_list_iter().count()
        };

        let cur_playing_visual = self
            .get_cur_playing_index()
            .and_then(|idx| self.actual_to_visual_index(idx));

        (0..count).map(move |visual_i| {
            let actual_i = self.visual_to_actual_index(visual_i);

            let ls = self
                .list
                .get_song_from_idx(actual_i)
                .expect("BUG: visual_to_actual_index returned out-of-bounds index");

            let first_field: Cow<'_, str> = if Some(visual_i) == cur_playing_visual {
                match self.play_status {
                    PlayState::NotPlaying => Cow::Borrowed(">>>"),
                    PlayState::Playing(_) => Cow::Borrowed(""),
                    PlayState::Paused(_) => Cow::Borrowed(""),
                    PlayState::Error(_) => Cow::Borrowed(">>>"),
                    PlayState::Buffering(_) => Cow::Borrowed(""),
                }
            } else if self.play_next_queue.contains(&ls.id) {
                Cow::Borrowed(" +")
            } else {
                self.cached_row_numbers
                    .get(visual_i)
                    .map(|s| Cow::Borrowed(s as &str))
                    .unwrap_or_else(|| Cow::Owned((visual_i + 1).to_string()))
            };

            iter::once(first_field).chain(ls.get_fields([
                ListSongDisplayableField::DownloadStatus,
                ListSongDisplayableField::TrackNo,
                ListSongDisplayableField::Artists,
                ListSongDisplayableField::Album,
                ListSongDisplayableField::Song,
                ListSongDisplayableField::Duration,
                ListSongDisplayableField::Year,
            ]))
        })
    }

    fn get_headings(&self) -> impl Iterator<Item = &'static str> {
        [
            "p#", "", "t#", "Artist", "Album", "Song", "Duration", "Year",
        ]
        .into_iter()
    }

    fn get_highlighted_row(&self) -> Option<usize> {
        self.get_cur_playing_index()
            .and_then(|idx| self.actual_to_visual_index(idx))
    }

    fn get_mut_state(&mut self) -> &mut ScrollingTableState {
        &mut self.widget_state
    }
}

impl HasTitle for Playlist {
    fn get_title(&self) -> Line<'static> {
        {
            let cached = self.cached_title.borrow();
            if let Some(title) = cached.as_ref() {
                return title.clone();
            }
        }
        let shuffle_indicator = if self.shuffle_enabled {
            " [SHUFFLE]"
        } else {
            ""
        };

        let resolve_indicator = if self.resolving_audio {
            " [RESOLVING]"
        } else {
            ""
        };

        let next_indicator = if !self.play_next_queue.is_empty() {
            format!(" [NEXT: {}]", self.play_next_queue.len())
        } else {
            String::new()
        };

        let song_count = self.list.get_list_iter().len();
        let base = format!(
            "Local playlist - {song_count} songs{shuffle_indicator}{resolve_indicator}{next_indicator}"
        );

        let title = if !self.search_text.is_empty() {
            let search_indicator = format!(" [SEARCH: {}]", self.search_text);
            if self.search_indices.is_empty() {
                Line::from(vec![
                    Span::raw(base),
                    Span::styled(search_indicator, Style::new().fg(Color::Red)),
                ])
            } else {
                Line::from(base + &search_indicator)
            }
        } else if self.search_enabled {
            Line::from(base + " [SEARCH]")
        } else {
            Line::from(base)
        };

        *self.cached_title.borrow_mut() = Some(title.clone());
        title
    }
}

impl SongListComponent for Playlist {
    fn get_song_from_idx(&self, idx: usize) -> Option<&ListSong> {
        self.list.get_list_iter().nth(idx)
    }
}

fn playback_stream(
    server: crate::app::server::ArcServer,
    id: ListSongID,
    decoder: Box<dyn Source<Item = f32> + Send + 'static>,
) -> impl Stream<Item = MutationFn<Playlist>> + Send + 'static {
    let (tx, rx) = tokio::sync::mpsc::unbounded_channel();
    let play_stream = server.player.play_song(decoder, id);

    tokio::spawn(async move {
        let mut play_stream = play_stream;
        while let Some(update) = play_stream.next().await {
            let mutation: MutationFn<Playlist> = match update {
                PlayUpdate::PlayProgress(d, id) => {
                    Box::new(move |this: &mut Playlist| this.handle_set_song_play_progress(d, id))
                }
                PlayUpdate::Playing(d, id) => {
                    Box::new(move |this: &mut Playlist| this.handle_playing(d, id))
                }
                PlayUpdate::DonePlaying(id) => {
                    Box::new(move |this: &mut Playlist| this.handle_done_playing(id))
                }
            };
            let _ = tx.send(mutation);
        }
    });

    UnboundedReceiverStream::new(rx)
}

impl Playlist {
    pub fn new(volume: Percentage) -> (Self, Effects<Self>) {
        let task = Effects::none();

        let mut playlist = Playlist {
            volume,
            play_status: PlayState::NotPlaying,
            list: Default::default(),
            id_to_index_cache: HashMap::new(),
            cur_played_dur: None,
            cur_selected: 0,
            queue_status: QueueState::NotQueued,
            widget_state: Default::default(),
            shuffle_enabled: false,
            shuffle_indices: Vec::new(),
            shuffle_visual_map: Vec::new(),
            shuffle_seed: SystemTime::now()
                .duration_since(SystemTime::UNIX_EPOCH)
                .unwrap_or_default()
                .as_secs(),
            active_downloads: Arc::new(std::sync::Mutex::new(Vec::new())),
            download_queue: VecDeque::new(),
            search_enabled: false,
            search_text: String::new(),
            search_indices: Vec::new(),
            search_visual_map: Vec::new(),
            pre_search_selected: 0,
            loaded_from_autosave: false,
            preloaded_sources: HashMap::new(),
            play_next_queue: VecDeque::new(),
            resolving_audio: false,
            resolve_remaining: 0,
            cached_row_numbers: Vec::new(),
            cached_title: RefCell::new(None),
        };

        playlist.rebuild_row_numbers();
        (playlist, task)
    }

    pub fn volume(&self) -> Percentage {
        self.volume
    }

    pub fn shuffle_enabled(&self) -> bool {
        self.shuffle_enabled
    }

    pub fn stop_song_id(&self, song_id: ListSongID) -> Effects<Self> {
        Effects::new(move |_: &crate::app::server::ArcServer| async move {
            Box::new(move |this: &mut Playlist| {
                this.handle_stopped(Stopped(song_id));
                Effects::none()
            }) as Box<dyn FnOnce(&mut Playlist) -> Effects<Playlist> + Send>
        })
    }

    pub fn get_cur_played_dur(&self) -> Option<Duration> {
        self.cur_played_dur
    }

    fn prepare_playback_id(&mut self, id: ListSongID) -> Effects<Self> {
        self.drop_unscoped_from_id(id);
        self.cur_played_dur = None;
        Effects::none()
    }

    fn start_buffering(
        &mut self,
        id: ListSongID,
        stop_song_id: Option<ListSongID>,
        mut effect: Effects<Self>,
    ) -> Effects<Self> {
        self.play_status = PlayState::Buffering(id);
        self.queue_status = QueueState::NotQueued;
        if let Some(cur_id) = stop_song_id {
            effect = effect.push(self.stop_song_id(cur_id));
        }
        effect
    }

    pub fn play_song(&mut self, id: ListSongID) -> Effects<Self> {
        // Clear Failed status so the user can retry explicitly.
        if let Some(idx) = self.get_index_from_id(id)
            && let Some(song) = self.list.get_list_iter_mut().nth(idx)
            && matches!(song.download_status, DownloadStatus::Failed)
        {
            song.download_status = DownloadStatus::None;
        }
        let mut effect = self.prepare_playback_id(id);

        if let Some(song_index) = self.get_index_from_id(id) {
            let stop_song_id = self.get_cur_playing_id();
            effect = self.start_buffering(id, stop_song_id, effect);

            // Prefer cache-backed decoder: avoids keeping a full SharedBuffer alive.
            let video_id = self
                .list
                .get_list_iter()
                .nth(song_index)
                .map(|s| s.video_id.get_raw().to_string());
            let cache_decoder = video_id
                .as_deref()
                .and_then(create_decoder_from_cache)
                .map(|d| Box::new(d) as Box<dyn Source<Item = f32> + Send + 'static>);

            if let Some(decoder) = cache_decoder {
                let task = Effects::new_stream(
                    move |server: &crate::app::server::ArcServer| {
                        playback_stream(Arc::clone(server), id, decoder)
                    }
                );
                effect = effect.push(task);
            } else if let Some(preloaded) = self.preloaded_sources.remove(&id) {
                let task = Effects::new_stream(
                    move |server: &crate::app::server::ArcServer| {
                        playback_stream(Arc::clone(server), id, preloaded)
                    }
                );
                effect = effect.push(task);
            } else {
                effect = effect.push(
                    Effects::new(|server: &crate::app::server::ArcServer| {
                        server.player.stop();
                        async move {
                            Box::new(|_: &mut Playlist| Effects::none())
                                as Box<dyn FnOnce(&mut Playlist) -> Effects<Playlist> + Send>
                        }
                    })
                );
                effect = effect.push(self.download_song(id));
            }
        } else {
            debug!("play_song called with unknown id {id:?}");
        }
        effect
    }

    fn rebuild_row_numbers(&mut self) {
        let n = self.list.get_list_iter().len().max(1);
        self.cached_row_numbers = (0..n).map(|i| (i + 1).to_string()).collect();
    }

    pub fn reset(&mut self) -> Effects<Self> {
        let mut effect = Effects::none();

        if let Some(cur_id) = self.get_cur_playing_id() {
            effect = self.stop_song_id(cur_id);
        }

        self.cancel_all_downloads();
        self.clear();
        effect
    }

    pub fn deduplicate(&mut self) {
        let removed = self.list.deduplicate();
        if removed > 0 {
            debug!(%removed, "Removed duplicate songs from playlist");
        }
        self.rebuild_id_cache();
        if removed > 0 {
            if self.shuffle_enabled {
                self.generate_shuffle_indices();
            }
            self.update_search_indices();
            self.rebuild_row_numbers();
            self.cached_title.borrow_mut().take();
        }
    }

    pub fn shuffle_seed(&self) -> u64 {
        self.shuffle_seed
    }

    pub fn loaded_from_autosave(&self) -> bool {
        self.loaded_from_autosave
    }

    pub fn set_loaded_from_autosave(&mut self, v: bool) {
        self.loaded_from_autosave = v;
    }

    pub fn enable_shuffle(&mut self, seed: u64) {
        self.shuffle_enabled = true;
        self.shuffle_seed = seed;
        self.generate_shuffle_indices();
        // Keep cur_selected in sync with the shuffle mapping so the visual
        // highlight matches what's playing (same logic as toggle_shuffle).
        if let (Some(_current_id), Some(playing_idx)) =
            (self.get_cur_playing_id(), self.get_cur_playing_index())
        {
            if let Some(shuffled_pos) =
                self.shuffle_visual_map
                    .get(playing_idx)
                    .copied()
                    .flatten()
            {
                self.cur_selected = shuffled_pos;
            }
        } else {
            self.cur_selected = 0.min(self.get_max_visual_index());
        }
        self.rebuild_row_numbers();
    }

    pub fn clear(&mut self) {
        self.cur_played_dur = None;
        self.play_status = PlayState::NotPlaying;
        self.list.clear();
        self.id_to_index_cache.clear();
        self.shuffle_indices.clear();
        self.shuffle_visual_map.clear();
        self.search_indices.clear();
        self.search_visual_map.clear();
        self.download_queue.clear();
        self.play_next_queue.clear();
        self.preloaded_sources.clear();
        self.cur_selected = 0;
        cache_clear();
        self.rebuild_row_numbers();
        self.cached_title.borrow_mut().take();
    }

    pub fn play_prev(&mut self) -> Effects<Self> {
        let cur = &self.play_status;
        match cur {
            PlayState::NotPlaying  => {
                debug!("play_prev: stopped, jumping to last song");
                let last_visual = self.get_max_visual_index();
                let last_actual = self.visual_to_actual_index(last_visual);
                if let Some(last_id) = self.get_id_from_index(last_actual) {
                    self.cur_selected = last_visual;
                    self.play_song(last_id)
                } else {
                    debug!("play_prev: queue is empty");
                    Effects::none()
                }
            }
            PlayState::Paused(_)
            | PlayState::Playing(_)
            | PlayState::Buffering(_)
            | PlayState::Error(_) => {
                if let Some(prev_song_id) = self.get_prev_song_id() {
                    self.play_song(prev_song_id)
                } else {
                    debug!("play_prev: at first song, wrapping to last");
                    let last_visual = self.get_max_visual_index();
                    let last_actual = self.visual_to_actual_index(last_visual);
                    if let Some(last_id) = self.get_id_from_index(last_actual) {
                        self.cur_selected = last_visual;
                        self.play_song(last_id)
                    } else {
                        Effects::none()
                    }
                }
            }
        }
    }

    pub fn handle_song_downloaded(&mut self, id: ListSongID) -> Effects<Self> {
        let start = std::time::Instant::now();
        if let PlayState::Buffering(target_id) = self.play_status
            && target_id == id
        {
            debug!(
                "play_attempt: song_id={:?}, state=Buffering, ms_since_download={}",
                id,
                start.elapsed().as_millis()
            );
            if matches!(self.queue_status, QueueState::Queued(_)) {
                debug!(
                    "autoplay_started: song_id={:?}, ms_to_start={}",
                    id,
                    start.elapsed().as_millis()
                );
            } else {
                debug!(
                    "play_started: song_id={:?}, ms_to_start={}",
                    id,
                    start.elapsed().as_millis()
                );
            }
            return Effects::none();
        }
        debug!(
            "download_handled_not_playing: song_id={:?}, state={:?}",
            id, self.play_status
        );
        Effects::none()
    }

    pub fn increase_volume(&mut self, inc: i8) {
        self.volume.0 = self.volume.0.saturating_add_signed(inc).clamp(0, 100);
    }

    pub fn set_volume(&mut self, new_vol: u8) {
        self.volume.0 = new_vol.clamp(0, 100);
    }

    pub fn push_song_list(
        &mut self,
        song_list: Vec<ListSong>,
    ) -> (ListSongID, Effects<Self>) {
        let was_playing = self.get_cur_playing_id();
        let first_id = self.list.push_song_list(song_list);
        self.rebuild_id_cache();

        if self.shuffle_enabled {
            self.generate_shuffle_indices();

            if let (Some(_current_id), Some(playing_idx)) =
                (was_playing, self.get_cur_playing_index())
            {
                if let Some(shuffled_pos) =
                    self.shuffle_indices.iter().position(|&i| i == playing_idx)
                {
                    self.cur_selected = shuffled_pos;
                }
            } else {
                self.cur_selected = 0.min(self.get_max_visual_index());
            }
        }

        if !self.search_text.is_empty() {
            self.update_search_indices();
            self.cur_selected = self.cur_selected.min(self.get_max_visual_index());
        }

        self.rebuild_row_numbers();
        self.cached_title.borrow_mut().take();
        (first_id, Effects::none())
    }

    pub fn play_next_or_stop(&mut self, prev_id: ListSongID) -> Effects<Self> {
        self.play_next_inner(prev_id, "finishing playback")
    }

    pub fn autoplay_next_or_stop(&mut self, prev_id: ListSongID) -> Effects<Self> {
        self.play_next_inner(prev_id, "resetting play status")
    }

    fn reshuffle_or_wrap(&mut self) -> usize {
        if self.shuffle_enabled {
            self.shuffle_seed = SystemTime::now()
                .duration_since(SystemTime::UNIX_EPOCH)
                .unwrap_or_default()
                .as_secs();
            self.generate_shuffle_indices();
        }
        0
    }

    fn play_next_inner(
        &mut self,
        prev_id: ListSongID,
        no_next_msg: &str,
    ) -> Effects<Self> {
        let current_id = self.get_cur_playing_id();
        match &self.play_status {
            PlayState::NotPlaying  => {
                debug!("Asked to play next, but not currently playing");
                Effects::none()
            }
            PlayState::Paused(_)
            | PlayState::Playing(_)
            | PlayState::Buffering(_)
            | PlayState::Error(_) => {
                let Some(id) = current_id else {
                    return Effects::none();
                };
                if id > prev_id {
                    debug!(
                        "play_next_inner: newer song already playing (id={id:?} > prev={prev_id:?})"
                    );
                    return Effects::none();
                }

                // Check play-next queue first (user-enqueued "play next" items)
                if let Some(next_id) = self.play_next_queue.pop_front() {
                    self.cached_title.borrow_mut().take();
                    return self.play_song(next_id);
                }

                if let Some(next_song_id) = self.get_next_song_id() {
                    self.play_song(next_song_id)
                } else {
                    debug!("No next song - {no_next_msg}, reshuffling/wrapping");
                    let first_visual = self.reshuffle_or_wrap();
                    let first_actual = self.visual_to_actual_index(first_visual);
                    if let Some(first_id) = self.get_id_from_index(first_actual) {
                        self.cur_selected = first_visual;
                        self.play_song(first_id)
                    } else {
                        self.queue_status = QueueState::NotQueued;
                        self.stop_song_id(id)
                    }
                }
            }
        }
    }

    pub fn download_upcoming_from_id(&mut self, id: ListSongID) -> Effects<Self> {
        let Some(song_index) = self.get_index_from_id(id) else {
            return Effects::none();
        };

        debug!(
            "download_upcoming_from_id: START for id={:?}, index={}",
            id, song_index
        );

        // Build list of song IDs in scope: [play-next, +1, +2]
        // The current song has its own streaming pipeline and is excluded.
        // Play-next entries have download priority since they play before natural next.
        let mut song_ids: Vec<ListSongID> = Vec::new();

        // Add play-next queue entries to scope (user-enqueued items have priority)
        for pn_id in self.play_next_queue.iter().take(SONGS_AHEAD_TO_BUFFER) {
            if !song_ids.contains(pn_id) && self.get_index_from_id(*pn_id).is_some() {
                song_ids.push(*pn_id);
            }
        }

        if self.shuffle_enabled {
            let Some(visual_index) = self.actual_to_visual_index(song_index) else {
                return Effects::none();
            };

            for offset in 1..=SONGS_AHEAD_TO_BUFFER {
                let next_pos = visual_index.saturating_add(offset);
                if next_pos < self.shuffle_indices.len() {
                    let next_actual = self.shuffle_indices[next_pos];
                    if let Some(next_id) = self.get_id_from_index(next_actual)
                        && !song_ids.contains(&next_id)
                    {
                        song_ids.push(next_id);
                    }
                }
            }
        } else {
            for offset in 1..=SONGS_AHEAD_TO_BUFFER {
                if let Some(next_song) = self.get_song_from_idx(song_index.saturating_add(offset))
                    && !song_ids.contains(&next_song.id)
                {
                    song_ids.push(next_song.id);
                }
            }
        }

        // Log what songs are in scope with their current status
        for &sid in &song_ids {
            if let Some(idx) = self.get_index_from_id(sid)
                && let Some(s) = self.list.get_list_iter().nth(idx)
            {
                debug!(
                    "  scope_song: id={:?}, video_id={}, status={:?}",
                    sid,
                    s.video_id.get_raw(),
                    s.download_status
                );
            }
        }

        // Cancel downloads not in scope.
        // Include the current song in scope to prevent cancelling its own download.
        let mut cancel_scope = vec![id];
        cancel_scope.extend(&song_ids);
        self.cancel_out_of_scope_downloads(&cancel_scope);

        debug!(
            "download_upcoming_from_id: queue BEFORE clear: {:?}",
            self.download_queue
        );

        // Clear existing download queue and add new songs
        // BUT: preserve songs that are already downloaded - they don't need to be re-queued
        self.download_queue.clear();
        for song_id in &song_ids {
            let status = if let Some(idx) = self.get_index_from_id(*song_id) {
                self.get_song_from_idx(idx).map(|s| &s.download_status)
            } else {
                None
            };

            match status {
                Some(DownloadStatus::Downloaded) => {
                    debug!(
                        "download_upcoming_from_id: skipping {:?} (already downloaded)",
                        song_id
                    );
                }
                Some(DownloadStatus::Failed) => {
                    debug!(
                        "download_upcoming_from_id: skipping {:?} (previously failed)",
                        song_id
                    );
                }
                _ => {
                    self.download_queue.push_back(*song_id);
                }
            }
        }

        debug!(
            "download_upcoming_from_id: queue AFTER filtering: {:?}",
            self.download_queue
        );

        // Start only the first download (current song).
        // Others are started sequentially as downloads complete.
        // Single download = no bandwidth contention with the song user selected.
        let mut combined_effect = Effects::none();
        if let Some(first_id) = self.download_queue.pop_front() {
            debug!(
                "download_upcoming_from_id: STARTING FIRST DOWNLOAD: {:?}",
                first_id
            );
            combined_effect = combined_effect.push(self.download_song(first_id));
        } else {
            debug!(
                "download_upcoming_from_id: no download needed (all in scope already downloaded)"
            );
        }

        combined_effect
    }

    pub fn download_song(&mut self, id: ListSongID) -> Effects<Self> {
        let Some(song_index) = self.get_index_from_id(id) else {
            debug!("download_song: song id {:?} not found", id);
            self.play_status = PlayState::NotPlaying;
            return Effects::none();
        };

        let song = match self.list.get_list_iter_mut().nth(song_index) {
            Some(s) => s,
            None => {
                debug!(
                    "download_song: index {} for id {:?} out of bounds after getting index",
                    song_index, id
                );
                self.play_status = PlayState::NotPlaying;
                return Effects::none();
            }
        };

        let video_id = song.video_id.get_raw().to_string();
        debug!("download_song: {}", video_id);

        match &song.download_status {
            DownloadStatus::Queued => {
                let has_active = self
                    .active_downloads
                    .lock()
                    .unwrap_or_warn()
                    .iter()
                    .any(|(sid, _)| *sid == id);
                if has_active {
                    debug!(
                        "download_song: {} already queued with active download",
                        video_id
                    );
                    return Effects::none();
                }
                warn!(
                    "download_song: {} status=Queued but no active download — possible invariant violation, proceeding",
                    video_id
                );
            }
            DownloadStatus::Downloading(_) => {
                debug!("download_song: {} already downloading", video_id);
                return Effects::none();
            }
            DownloadStatus::Failed => {
                debug!(
                    "download_song: {} previously failed — popping from queue",
                    video_id
                );
                self.download_queue.pop_front();
                if let Some(next_id) = self.download_queue.front().copied() {
                    return self.download_song(next_id);
                }
                debug!(
                    "download_song: {} failed and no queued songs remaining",
                    video_id
                );
                self.play_status = PlayState::NotPlaying;
                return Effects::none();
            }
            _ => {}
        };

        // Cancel existing download for this song if any
        {
            let downloads = self.active_downloads.lock().unwrap_or_warn();
            if let Some((_, task)) = downloads.iter().find(|(sid, _)| *sid == id) {
                debug!(
                    "download_song: cancelling existing download for {}",
                    video_id
                );
                task.cancel_token.cancel();
            }
        }

        let cancel_token = Arc::new(tokio_util::sync::CancellationToken::new());
        let cancel_token_for_stream = cancel_token.clone();
        debug!("download_song: starting download for {}", video_id);

        let effect = Effects::new_stream(
            move |server: &crate::app::server::ArcServer| {
                let (tx, rx) = tokio::sync::mpsc::unbounded_channel();
                let yt_cmd = server.config.yt_dlp_command.clone();
                let pt = server.po_token.clone();
                let vid = video_id.clone();
                let song_id = id;

                tokio::spawn(async move {
                    let emit: MutationFn<Playlist> = Box::new(move |this: &mut Playlist| {
                        this.handle_song_download_progress_update(
                            DownloadProgressUpdate::Downloading, song_id,
                        )
                    });
                    let _ = tx.send(emit);

                    match download_and_decode(
                        &yt_cmd, &vid, pt.as_deref(), None, None,
                        (*cancel_token_for_stream).clone(),
                    ).await {
                        Ok(decoder) => {
                            let decoder = Box::new(decoder)
                                as Box<dyn Source<Item = f32> + Send>;
                            let emit: MutationFn<Playlist> = Box::new(move |this: &mut Playlist| {
                                this.handle_song_download_progress_update(
                                    DownloadProgressUpdate::Completed(decoder), song_id,
                                )
                            });
                            let _ = tx.send(emit);
                        }
                        Err(e) => {
                            let err = e.to_string();
                            let emit: MutationFn<Playlist> = Box::new(move |this: &mut Playlist| {
                                this.handle_song_download_progress_update(
                                    DownloadProgressUpdate::Error(err), song_id,
                                )
                            });
                            let _ = tx.send(emit);
                        }
                    }
                });

                UnboundedReceiverStream::new(rx)
            }
        );

        let mut downloads = self.active_downloads.lock().unwrap_or_warn();
        downloads.retain(|(song_id, _)| *song_id != id);
        downloads.push((id, DownloadTask { cancel_token }));

        song.download_status = DownloadStatus::Queued;
        effect
    }

    pub fn drop_unscoped_from_id(&mut self, id: ListSongID) {
        let Some(song_index) = self.get_index_from_id(id) else {
            return;
        };

        let forward_limit = song_index.saturating_add(SONGS_AHEAD_TO_BUFFER);
        let backwards_limit = song_index.saturating_sub(SONGS_BEHIND_TO_SAVE);

        let mut downloads = self.active_downloads.lock().unwrap_or_warn();
        downloads.retain(|(song_id, task)| {
            if let Some(idx) = self.get_index_from_id(*song_id)
                && (idx < backwards_limit || idx >= forward_limit)
                && !self.play_next_queue.contains(song_id)
            {
                task.cancel_token.cancel();
                return false;
            }
            true
        });

        for (idx, song) in self.list.get_list_iter_mut().enumerate() {
            if (idx < backwards_limit || idx >= forward_limit)
                && !self.play_next_queue.contains(&song.id)
            {
                song.download_status = DownloadStatus::None;
            }
        }

        let out_of_scope: Vec<ListSongID> = self
            .preloaded_sources
            .keys()
            .filter(|id| {
                self.get_index_from_id(**id)
                    .is_none_or(|idx| idx < backwards_limit || idx >= forward_limit)
            })
            .filter(|id| !self.play_next_queue.contains(id))
            .copied()
            .collect();
        for id in out_of_scope {
            self.preloaded_sources.remove(&id);
        }
    }

    pub fn get_cur_playing_id(&self) -> Option<ListSongID> {
        match self.play_status {
            PlayState::Error(id)
            | PlayState::Playing(id)
            | PlayState::Paused(id)
            | PlayState::Buffering(id) => Some(id),
            PlayState::NotPlaying  => None,
        }
    }

    pub fn get_cur_playing_song(&self) -> Option<&ListSong> {
        self.get_cur_playing_id()
            .and_then(|id| self.get_song_from_id(id))
    }

    pub fn status_bar_icon(&self) -> char {
        match self.play_status {
            PlayState::Playing(id) => {
                if self
                    .get_song_from_id(id)
                    .is_some_and(|s| !matches!(s.download_status, DownloadStatus::Downloaded))
                {
                    ''
                } else {
                    ''
                }
            }
            PlayState::Buffering(_) => '',
            PlayState::Paused(_) => '',
            PlayState::Error(_) => '',
            PlayState::NotPlaying  => '',
        }
    }

    pub fn get_next_song(&self) -> Option<&ListSong> {
        self.get_cur_playing_id()
            .and_then(|_| self.get_next_song_id())
            .and_then(|next_id| self.get_song_from_id(next_id))
    }

    fn rebuild_id_cache(&mut self) {
        self.id_to_index_cache = self
            .list
            .get_list_iter()
            .enumerate()
            .map(|(i, s)| (s.id, i))
            .collect();
    }

    pub fn get_index_from_id(&self, id: ListSongID) -> Option<usize> {
        self.id_to_index_cache
            .get(&id)
            .copied()
            // Fallback: if cache is stale, compute on-the-fly
            .or_else(|| self.list.get_list_iter().position(|s| s.id == id))
    }

    pub fn get_id_from_index(&self, index: usize) -> Option<ListSongID> {
        self.get_song_from_idx(index).map(|s| s.id)
    }

    pub fn get_mut_song_from_id(&mut self, id: ListSongID) -> Option<&mut ListSong> {
        let idx = self.get_index_from_id(id)?;
        self.list.get_list_iter_mut().nth(idx)
    }

    pub fn get_song_from_id(&self, id: ListSongID) -> Option<&ListSong> {
        let idx = self.get_index_from_id(id)?;
        self.list.get_list_iter().nth(idx)
    }

    pub fn check_id_is_cur(&self, check_id: ListSongID) -> bool {
        self.get_cur_playing_id().is_some_and(|id| id == check_id)
    }

    pub fn get_cur_playing_index(&self) -> Option<usize> {
        self.get_cur_playing_id()
            .and_then(|id| self.get_index_from_id(id))
    }
    pub fn go_to_first(&mut self) {
        self.cur_selected = 0;
    }

    pub fn go_to_last(&mut self) {
        self.cur_selected = self.list.get_list_iter().len().saturating_sub(1);
    }
}

impl Playlist {
    pub async fn handle_tick(&mut self) {}

    pub fn handle_seek(
        &mut self,
        _duration: Duration,
        _direction: SeekDirection,
    ) -> Effects<Self> {
        Effects::new(|_: &crate::app::server::ArcServer| async move {
            Box::new(|_: &mut Playlist| Effects::none()) as Box<dyn FnOnce(&mut Playlist) -> Effects<Playlist> + Send>
        })
    }

    pub fn handle_seek_to(&mut self, _position: Duration) -> Effects<Self> {
        let _id = match self.play_status {
            PlayState::Playing(id) | PlayState::Paused(id) => id,
            _ => return Effects::none(),
        };

        Effects::new(|_: &crate::app::server::ArcServer| async move {
            Box::new(|_: &mut Playlist| Effects::none()) as Box<dyn FnOnce(&mut Playlist) -> Effects<Playlist> + Send>
        })
    }

    pub fn handle_next(&mut self) -> Effects<Self> {
        match self.play_status {
            PlayState::NotPlaying  => {
                debug!("Asked to play next, but not currently playing");
                Effects::none()
            }
            PlayState::Paused(id)
            | PlayState::Playing(id)
            | PlayState::Buffering(id)
            | PlayState::Error(id) => self.play_next_or_stop(id),
        }
    }

    pub fn handle_previous(&mut self) -> Effects<Self> {
        self.play_prev()
    }

    pub fn pauseplay(&mut self) -> Effects<Self> {
        let _id = match self.play_status {
            PlayState::Playing(id) => {
                self.play_status = PlayState::Paused(id);
                id
            }
            PlayState::Paused(id) => {
                self.play_status = PlayState::Playing(id);
                id
            }
            _ => return Effects::none(),
        };

        Effects::new(|server: &crate::app::server::ArcServer| {
            server.player.pause();
            async move {
                Box::new(|_: &mut Playlist| Effects::none()) as Box<dyn FnOnce(&mut Playlist) -> Effects<Playlist> + Send>
            }
        })
    }

    pub fn resume(&mut self) -> Effects<Self> {
        let _id = match self.play_status {
            PlayState::Paused(id) => {
                self.play_status = PlayState::Playing(id);
                id
            }
            _ => return Effects::none(),
        };

        Effects::new(|server: &crate::app::server::ArcServer| {
            server.player.pause();
            async move {
                Box::new(|_: &mut Playlist| Effects::none()) as Box<dyn FnOnce(&mut Playlist) -> Effects<Playlist> + Send>
            }
        })
    }

    pub fn pause(&mut self) -> Effects<Self> {
        let _id = match self.play_status {
            PlayState::Playing(id) => {
                self.play_status = PlayState::Paused(id);
                id
            }
            _ => return Effects::none(),
        };

        Effects::new(|server: &crate::app::server::ArcServer| {
            server.player.pause();
            async move {
                Box::new(|_: &mut Playlist| Effects::none()) as Box<dyn FnOnce(&mut Playlist) -> Effects<Playlist> + Send>
            }
        })
    }

    pub fn stop(&mut self) -> Effects<Self> {
        self.play_status = PlayState::NotPlaying;
        self.preloaded_sources.clear();
        cache_clear();
        self.cancel_all_downloads();
        Effects::new(|server: &crate::app::server::ArcServer| {
            server.player.stop();
            async move {
                Box::new(move |this: &mut Playlist| {
                    this.handle_all_stopped(AllStopped);
                    Effects::none()
                }) as Box<dyn FnOnce(&mut Playlist) -> Effects<Playlist> + Send>
            }
        })
    }

    pub fn play_selected(&mut self) -> Effects<Self> {
        if !self.search_text.is_empty() && self.search_indices.is_empty() {
            return Effects::none();
        }
        if self.list.get_list_iter().len() == 0 {
            return Effects::none();
        }

        let actual_index = self.visual_to_actual_index(self.cur_selected);
        let Some(id) = self.get_id_from_index(actual_index) else {
            return Effects::none();
        };
        self.play_song(id)
    }

    pub fn delete_selected(&mut self) -> Effects<Self> {
        if !self.search_text.is_empty() && self.search_indices.is_empty() {
            return Effects::none();
        }

        let mut return_task = Effects::none();

        if self.list.get_list_iter().len() == 0 {
            return return_task;
        }

        let visual_index_before = self.cur_selected;
        let actual_index = self.visual_to_actual_index(visual_index_before);
        let deleted_id = self.get_id_from_index(actual_index);

        if let Some(cur_playing_id) = self.get_cur_playing_id()
            && Some(actual_index) == self.get_cur_playing_index()
        {
            self.play_status = PlayState::NotPlaying;
            return_task = self.stop_song_id(cur_playing_id);
        }

        // Cancel any in-flight download for the deleted song and remove from queue
        if let Some(id) = deleted_id {
            self.cancel_song_download(id);
            self.download_queue.retain(|qid| *qid != id);
        }

        // Delete from main list first
        self.list.remove_song_index(actual_index);
        self.rebuild_id_cache();

        // Rebuild search to ensure accuracy
        if !self.search_text.is_empty() {
            self.update_search_indices();
            self.cur_selected = if self.search_indices.is_empty() {
                0
            } else {
                visual_index_before.min(self.search_indices.len() - 1)
            };
        } else {
            let new_max = self.list.get_list_iter().len().saturating_sub(1);
            self.cur_selected = self.cur_selected.min(new_max);
        }

        // Adjust shuffle indices
        if self.shuffle_enabled {
            if let Some(pos) = self.shuffle_indices.iter().position(|&i| i == actual_index) {
                self.shuffle_indices.remove(pos);
            }
            for idx in &mut self.shuffle_indices {
                if *idx > actual_index {
                    *idx = idx.saturating_sub(1);
                }
            }
            self.shuffle_visual_map =
                build_visual_map(&self.shuffle_indices, self.list.get_list_iter().count());
        }

        self.rebuild_row_numbers();
        return_task
    }

    fn cancel_song_download(&self, id: ListSongID) {
        let token = {
            let mut downloads = self.active_downloads.lock().unwrap_or_warn();
            let pos = downloads.iter().position(|(song_id, _)| *song_id == id);
            pos.map(|p| downloads.swap_remove(p).1.cancel_token)
        };
        if let Some(token) = token {
            token.cancel();
        }
    }

    pub fn delete_all(&mut self) -> Effects<Self> {
        self.reset()
    }

    pub fn view_browser(&mut self) -> AppCallback {
        AppCallback::ChangeContext(WindowContext::Browser)
    }

    pub fn toggle_shuffle(&mut self) -> Effects<Self> {
        self.shuffle_enabled = !self.shuffle_enabled;

        if self.shuffle_enabled {
            self.shuffle_seed = SystemTime::now()
                .duration_since(SystemTime::UNIX_EPOCH)
                .unwrap_or_default()
                .as_secs();

            self.generate_shuffle_indices();

            if let (Some(_current_id), Some(playing_idx)) =
                (self.get_cur_playing_id(), self.get_cur_playing_index())
            {
                if let Some(shuffled_pos) =
                    self.shuffle_indices.iter().position(|&i| i == playing_idx)
                {
                    self.cur_selected = shuffled_pos;
                }
            } else {
                self.cur_selected = 0.min(self.get_max_visual_index());
            }
        } else {
            if let Some(playing_idx) = self.get_cur_playing_index() {
                self.cur_selected =
                    playing_idx.min(self.list.get_list_iter().len().saturating_sub(1));
            }
            self.shuffle_indices.clear();
            self.shuffle_visual_map.clear();
        }

        self.rebuild_row_numbers();
        self.cached_title.borrow_mut().take();
        self.regenerate_downloads_for_current()
    }

    fn generate_shuffle_indices(&mut self) {
        let len = self.list.get_list_iter().count();
        if len == 0 {
            self.shuffle_indices.clear();
            self.shuffle_visual_map.clear();
            return;
        }

        let mut indices: Vec<usize> = (0..len).collect();

        let mut rng = StdRng::seed_from_u64(self.shuffle_seed);
        for i in (1..len).rev() {
            let j = rng.random_range(0..=i);
            indices.swap(i, j);
        }

        if let Some(current_index) = self.get_cur_playing_index()
            && let Some(pos) = indices.iter().position(|&i| i == current_index)
        {
            indices.swap(0, pos);
        }

        self.shuffle_visual_map = build_visual_map(&indices, len);
        self.shuffle_indices = indices;
    }

    pub fn toggle_search(&mut self) -> Effects<Self> {
        self.search_enabled = !self.search_enabled;
        self.cached_title.borrow_mut().take();

        if self.search_enabled {
            self.pre_search_selected = self.cur_selected;
            self.search_text.clear();
            self.update_search_indices();
        } else {
            let _ = self.clear_search();
            self.cur_selected = self.pre_search_selected.min(self.get_max_visual_index());
        }

        Effects::none()
    }

    pub fn clear_search(&mut self) -> Effects<Self> {
        self.search_text.clear();
        self.cached_title.borrow_mut().take();
        self.update_search_indices();
        self.cur_selected = self.cur_selected.min(self.get_max_visual_index());
        Effects::none()
    }

    fn update_search_indices(&mut self) {
        let list_len = self.list.get_list_iter().count();
        let search_lower = self.search_text.to_lowercase();

        if search_lower.is_empty() {
            self.search_indices = (0..list_len).collect();
            self.search_visual_map = build_visual_map(&self.search_indices, list_len);
            return;
        }

        let words: Vec<&str> = search_lower.split_whitespace().collect();

        self.search_indices = self
            .list
            .get_list_iter()
            .enumerate()
            .filter_map(|(actual_idx, song)| {
                if words.iter().all(|word| {
                    song.title_lower.contains(word)
                        || song.album_lower.contains(word)
                        || song.artists_lower.contains(word)
                }) {
                    Some(actual_idx)
                } else {
                    None
                }
            })
            .collect();
        self.search_visual_map = build_visual_map(&self.search_indices, list_len);
        self.rebuild_row_numbers();
    }

    /// Maps a visual (display) index to an actual (list) index.
    ///
    /// The visual index is what the user sees (row position on screen). The actual
    /// index is the position in the underlying `list`.
    ///
    /// Three modes:
    /// - **Search** (`search_text` non-empty): uses `search_indices` (filtered list order).
    /// - **Shuffle** (`shuffle_enabled`): uses `shuffle_indices` (randomized order).
    /// - **Normal**: identity mapping (visual == actual).
    fn visual_to_actual_index(&self, visual_index: usize) -> usize {
        let list_len = self.list.get_list_iter().count();
        if list_len == 0 {
            return 0;
        }

        // Search mode: use original list order, ignore shuffle
        if !self.search_text.is_empty() {
            if self.search_indices.is_empty() {
                return 0;
            }
            let clamped = visual_index.min(self.search_indices.len() - 1);
            return self.search_indices[clamped];
        }

        // No search: apply shuffle if enabled
        let base_index = visual_index.min(list_len - 1);
        if self.shuffle_enabled && !self.shuffle_indices.is_empty() {
            self.shuffle_indices[base_index.min(self.shuffle_indices.len() - 1)]
        } else {
            base_index.min(list_len - 1)
        }
    }

    /// Reverse of [`visual_to_actual_index`]: given an actual (list) index, find
    /// its visual (display) position.
    ///
    /// Uses pre-built inverse maps for O(1) lookup instead of O(n) linear scan.
    /// Returns `None` if the index does not exist in the current visual mapping
    /// (e.g., it was filtered out by search).
    fn actual_to_visual_index(&self, actual_index: usize) -> Option<usize> {
        if !self.search_text.is_empty() {
            return self
                .search_visual_map
                .get(actual_index)
                .copied()
                .flatten();
        }

        if self.shuffle_enabled && !self.shuffle_indices.is_empty() {
            return self
                .shuffle_visual_map
                .get(actual_index)
                .copied()
                .flatten();
        }

        Some(actual_index)
    }

    /// Returns the next song to play after `_current_id`, respecting the current
    /// visual ordering (search → shuffle → natural). Used by autoplay / next-track.
    /// Returns `None` if already at the last visual position.
    fn get_next_song_id(&self) -> Option<ListSongID> {
        let current_visual = self
            .get_cur_playing_index()
            .and_then(|idx| self.actual_to_visual_index(idx))?;

        if current_visual >= self.get_max_visual_index() {
            return None;
        }

        let next_visual = current_visual.saturating_add(1);
        let next_actual = self.visual_to_actual_index(next_visual);
        self.get_id_from_index(next_actual)
    }

    fn get_prev_song_id(&self) -> Option<ListSongID> {
        let current_visual = self
            .get_cur_playing_index()
            .and_then(|idx| self.actual_to_visual_index(idx))?;

        if current_visual == 0 {
            return None;
        }

        let prev_visual = current_visual.saturating_sub(1);
        let prev_actual = self.visual_to_actual_index(prev_visual);
        self.get_id_from_index(prev_actual)
    }

    fn get_max_visual_index(&self) -> usize {
        let count = if !self.search_text.is_empty() {
            // Search mode: count of matching results
            self.search_indices.len()
        } else if self.shuffle_enabled {
            // Shuffle mode: count of shuffled items
            self.shuffle_indices.len()
        } else {
            // Normal mode: full list count
            self.list.get_list_iter().count()
        };

        count.saturating_sub(1)
    }

    fn cancel_all_downloads(&mut self) {
        let mut downloads = self.active_downloads.lock().unwrap_or_warn();
        for (_, task) in downloads.iter() {
            task.cancel_token.cancel();
        }
        downloads.clear();
        self.download_queue.clear();
        self.preloaded_sources.clear();
    }

    fn cancel_out_of_scope_downloads(&mut self, scope_ids: &[ListSongID]) {
        let removed_ids: Vec<ListSongID> = {
            let mut downloads = self.active_downloads.lock().unwrap_or_warn();
            let mut removed = Vec::new();
            downloads.retain(|(song_id, task)| {
                if scope_ids.contains(song_id) {
                    true
                } else {
                    task.cancel_token.cancel();
                    removed.push(*song_id);
                    false
                }
            });
            removed
        };
        for removed_id in &removed_ids {
            if let Some(song) = self.get_mut_song_from_id(*removed_id) {
                song.download_status = DownloadStatus::None;
            }
        }
        for id in &removed_ids {
            self.preloaded_sources.remove(id);
            self.download_queue.retain(|qid| qid != id);
        }
        let stale_preloaded: Vec<ListSongID> = self
            .preloaded_sources
            .keys()
            .filter(|id| !scope_ids.contains(id))
            .copied()
            .collect();
        for id in stale_preloaded {
            self.preloaded_sources.remove(&id);
        }
    }

    fn regenerate_downloads_for_current(&mut self) -> Effects<Self> {
        if let Some(current_id) = self.get_cur_playing_id() {
            self.drop_unscoped_from_id(current_id);
            self.download_upcoming_from_id(current_id)
        } else {
            Effects::none()
        }
    }

    pub fn handle_song_download_progress_update(
        &mut self,
        update: DownloadProgressUpdate,
        id: ListSongID,
    ) -> Effects<Self> {
        let video_id = self
            .get_song_from_id(id)
            .map(|s| s.video_id.get_raw().to_string())
            .unwrap_or_else(|| "unknown".to_string());

        match update {
            DownloadProgressUpdate::Downloading => {
                debug!("download_started: song_id={}", video_id);
                if let Some(idx) = self.get_index_from_id(id)
                    && let Some(song) = self.list.get_list_iter_mut().nth(idx)
                {
                    song.download_status = DownloadStatus::Downloading(Percentage(0));
                }
                Effects::none()
            }
            DownloadProgressUpdate::Completed(decoder) => {
                debug!("download_done: song_id={}", video_id);
                if let Some(idx) = self.get_index_from_id(id)
                    && let Some(s) = self.list.get_list_iter_mut().nth(idx)
                {
                    s.download_status = DownloadStatus::Downloaded;
                }
                self.active_downloads
                    .lock()
                    .unwrap_or_warn()
                    .retain(|(song_id, _)| *song_id != id);

                let mut effect = self.handle_song_downloaded(id);

                // If we were buffering for this song, play it directly
                if let PlayState::Buffering(target_id) = self.play_status
                    && target_id == id
                {
                    let task = Effects::new_stream(
                        move |server: &crate::app::server::ArcServer| {
                            playback_stream(Arc::clone(server), id, decoder)
                        }
                    );
                    effect = effect.push(task);
                } else {
                    // Pre-downloaded while still playing another song — store for later
                    self.preloaded_sources.insert(id, decoder);
                }

                if let Some(next_id) = self.download_queue.pop_front() {
                    debug!("queue_starting_next: song_id={:?}", next_id);
                    effect = effect.push(self.download_song(next_id));
                }
                effect
            }
            DownloadProgressUpdate::Error(e) => {
                if is_cancellation_error(&e) {
                    debug!("download_error: song_id={}, error={}", video_id, e);
                } else {
                    warn!("download_error: song_id={}, error={}", video_id, e);
                }
                if let Some(idx) = self.get_index_from_id(id)
                    && let Some(song) = self.list.get_list_iter_mut().nth(idx)
                {
                    song.download_status = DownloadStatus::Failed;
                }
                self.active_downloads
                    .lock()
                    .unwrap_or_warn()
                    .retain(|(song_id, _)| *song_id != id);

                let mut effect = Effects::none();
                // If we were buffering this song, surface the error and skip.
                if matches!(self.play_status, PlayState::Buffering(target) if target == id) {
                    if is_cancellation_error(&e) {
                        debug!("download failed while buffering, skipping: {}", e);
                    } else {
                        warn!("download failed while buffering, skipping: {}", e);
                    }
                    effect = effect.push(self.handle_set_to_error(id));
                }
                // Intentionally NOT popping from download_queue here:
                // cancelled prebuffer tasks would cascade-drain the queue.
                // Queue advancement is handled by the Completed handler
                // and regenerate_downloads_for_current.
                effect
            }
        }
    }

    pub fn handle_volume_update(&mut self, response: VolumeUpdate) {
        self.volume = response.0
    }

    pub fn handle_set_song_play_progress(
        &mut self,
        d: Duration,
        id: ListSongID,
    ) -> Effects<Self> {
        if !self.check_id_is_cur(id) {
            return Effects::none();
        }

        if d.is_zero() {
            debug!("play_progress: zero duration received for id={:?}", id);
        }
        self.cur_played_dur = Some(d);

        if let Some(duration_dif) = {
            let cur_dur = self
                .get_cur_playing_song()
                .and_then(|song| song.actual_duration);
            self.cur_played_dur
                .as_ref()
                .zip(cur_dur)
                .map(|(d1, d2)| d2.saturating_sub(*d1))
        } && duration_dif
            .saturating_sub(GAPLESS_PLAYBACK_THRESHOLD)
            .is_zero()
            && !matches!(self.queue_status, QueueState::Queued(_))
            && let Some(next_song) = self.get_next_song()
            && !matches!(
                &next_song.download_status,
                DownloadStatus::Downloaded | DownloadStatus::Failed
            )
        {
            let next_id = next_song.id;
            debug!("Queuing up song!");
            let effect = self.download_song(next_id);
            self.queue_status = QueueState::Queued(next_id);
            return effect;
        }

        Effects::none()
    }

    pub fn handle_done_playing(&mut self, id: ListSongID) -> Effects<Self> {
        if !self.check_id_is_cur(id) && self.queue_status != QueueState::Queued(id) {
            return Effects::none();
        }

        if self.queue_status == QueueState::Queued(id) {
            self.queue_status = QueueState::NotQueued;
            return Effects::none();
        }

        self.autoplay_next_or_stop(id)
    }

    pub fn handle_playing(
        &mut self,
        duration: Option<Duration>,
        id: ListSongID,
    ) -> Effects<Self> {
        if let Some(song) = self.get_mut_song_from_id(id) {
            song.actual_duration = duration;
        }

        match self.play_status {
            PlayState::Paused(p_id) if p_id == id => {
                self.play_status = PlayState::Playing(id);
            }
            PlayState::Buffering(b_id) if b_id == id => {
                self.play_status = PlayState::Playing(id);
            }
            _ => {}
        }
        self.regenerate_downloads_for_current()
    }

    pub fn handle_set_to_error(&mut self, id: ListSongID) -> Effects<Self> {
        debug!("Received message that song had a playback error {:?}", id);
        if self.check_id_is_cur(id) {
            debug!("Setting song state to Error {:?}", id);
            self.play_status = PlayState::Error(id);
            debug!("Skipping to next song after error");
            self.play_next_or_stop(id)
        } else {
            Effects::none()
        }
    }

    pub fn handle_stopped(&mut self, id: Stopped<ListSongID>) {
        let Stopped(id) = id;
        debug!("Received message that playback {:?} has been stopped", id);
        if self.check_id_is_cur(id) {
            debug!("Stopping {:?}", id);
            self.play_status = PlayState::NotPlaying;
            self.preloaded_sources.clear();
            cache_clear();
        }
    }

    pub fn handle_all_stopped(&mut self, _: AllStopped) {
        if matches!(self.play_status, PlayState::NotPlaying) {
            self.preloaded_sources.clear();
            cache_clear();
        }
    }
}
